use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum BiasCategory {
    /// Too much information — we notice things already primed in memory
    Memory,
    /// Not enough meaning — we fill in gaps with what we already know
    MeaningMaking,
    /// Need to act fast — we jump to conclusions and act on incomplete information
    ActionBias,
    /// What should we remember — we reduce events and lists to their key elements
    RecencyAndSaliency,
    /// Belief and confirmation
    BeliefAndConfirmation,
    /// Social and group dynamics
    SocialAndGroup,
    /// Probability and statistics
    ProbabilityAndStats,
    /// Self-perception and ego
    SelfPerception,
    /// Causal attribution
    CausalAttribution,
    /// Decision making under uncertainty
    DecisionMaking,
}

impl BiasCategory {
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::Memory => "Memory & Recall",
            Self::MeaningMaking => "Meaning-Making",
            Self::ActionBias => "Action & Inertia",
            Self::RecencyAndSaliency => "Recency & Salience",
            Self::BeliefAndConfirmation => "Belief & Confirmation",
            Self::SocialAndGroup => "Social & Group Dynamics",
            Self::ProbabilityAndStats => "Probability & Statistics",
            Self::SelfPerception => "Self-Perception",
            Self::CausalAttribution => "Causal Attribution",
            Self::DecisionMaking => "Decision Making",
        }
    }

    pub fn color_index(&self) -> u8 {
        match self {
            Self::Memory => 0,
            Self::MeaningMaking => 1,
            Self::ActionBias => 2,
            Self::RecencyAndSaliency => 3,
            Self::BeliefAndConfirmation => 4,
            Self::SocialAndGroup => 5,
            Self::ProbabilityAndStats => 6,
            Self::SelfPerception => 7,
            Self::CausalAttribution => 8,
            Self::DecisionMaking => 9,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Bias {
    pub name: &'static str,
    pub alt_names: &'static [&'static str],
    pub category: BiasCategory,
    pub description: &'static str,
    pub example: &'static str,
    pub severity: Severity,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum Severity {
    Low,
    Medium,
    High,
}

impl Severity {
    pub fn label(self) -> &'static str {
        match self {
            Self::Low => "Low",
            Self::Medium => "Medium",
            Self::High => "High",
        }
    }
}

pub static BIAS_CODEX: Lazy<Vec<Bias>> = Lazy::new(|| {
    vec![
        // ─── BELIEF & CONFIRMATION ────────────────────────────────────────────
        Bias {
            name: "Confirmation Bias",
            alt_names: &["confirmatory bias", "myside bias"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "The tendency to search for, interpret, focus on and remember information in a way that confirms one's preconceptions.",
            example: "Only reading news sources that agree with your political views.",
            severity: Severity::High,
        },
        Bias {
            name: "Belief Bias",
            alt_names: &["belief-based reasoning"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "An effect where someone's evaluation of the logical strength of an argument is biased by the believability of the conclusion.",
            example: "Accepting a logically flawed argument because the conclusion aligns with your existing beliefs.",
            severity: Severity::High,
        },
        Bias {
            name: "Backfire Effect",
            alt_names: &["backfire bias"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "A tendency to react to disconfirming evidence by strengthening one's previous beliefs.",
            example: "Becoming more convinced vaccines are harmful after reading evidence they are safe.",
            severity: Severity::High,
        },
        Bias {
            name: "Semmelweis Reflex",
            alt_names: &["semmelweis effect"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "The tendency to reject new evidence that contradicts a paradigm.",
            example: "Dismissing a scientific study because it contradicts long-held medical doctrine.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Illusory Truth Effect",
            alt_names: &["illusion of truth", "reiteration effect"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "The tendency to believe that a statement is true if it has been stated multiple times, regardless of its actual veracity.",
            example: "Believing a repeated advertising slogan is factually accurate.",
            severity: Severity::High,
        },
        Bias {
            name: "Continued Influence Effect",
            alt_names: &["misinformation effect", "continued influence"],
            category: BiasCategory::BeliefAndConfirmation,
            description: "Misinformation continues to influence memory and reasoning about an event, despite the misinformation having been corrected.",
            example: "Continuing to believe a retracted news story even after seeing the correction.",
            severity: Severity::High,
        },
        // ─── SELF-PERCEPTION ──────────────────────────────────────────────────
        Bias {
            name: "Dunning-Kruger Effect",
            alt_names: &["dunning kruger", "overconfidence bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency for unskilled individuals to overestimate their own ability and for experts to underestimate their own ability.",
            example: "A beginner programmer believing they know everything about software after finishing one tutorial.",
            severity: Severity::High,
        },
        Bias {
            name: "Overconfidence Effect",
            alt_names: &["overconfidence", "overconfidence bias"],
            category: BiasCategory::SelfPerception,
            description: "A tendency to have excessive confidence in one's own answers to questions.",
            example: "Being 99% sure of an answer that turns out to be wrong.",
            severity: Severity::High,
        },
        Bias {
            name: "Illusory Superiority",
            alt_names: &["lake wobegon effect", "better-than-average effect", "superiority bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to overestimate one's desirable qualities, and underestimate undesirable qualities, relative to other people.",
            example: "90% of drivers believing they are above-average drivers.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Bias Blind Spot",
            alt_names: &["blind spot bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to see oneself as less biased than other people, or to identify more cognitive biases in others than in oneself.",
            example: "Saying 'I'm not biased, but other people clearly are.'",
            severity: Severity::Medium,
        },
        Bias {
            name: "Self-Serving Bias",
            alt_names: &["self serving bias", "self-enhancement"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to claim more responsibility for successes than failures.",
            example: "Taking credit for a team win but blaming teammates for a loss.",
            severity: Severity::High,
        },
        Bias {
            name: "Optimism Bias",
            alt_names: &["optimistic bias", "unrealistic optimism"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to be over-optimistic, underestimating greatly the probability of undesirable outcomes.",
            example: "Believing you are less likely to get into a car accident than the average person.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Pessimism Bias",
            alt_names: &["pessimistic bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to overestimate the likelihood that bad things will happen.",
            example: "Assuming a new project will definitely fail despite positive evidence.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Impostor Syndrome",
            alt_names: &["impostor phenomenon", "imposter syndrome"],
            category: BiasCategory::SelfPerception,
            description: "A psychological occurrence in which an individual doubts their skills and has a persistent fear of being exposed as a fraud.",
            example: "A competent engineer feeling they don't deserve their job despite consistent positive feedback.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Naïve Realism",
            alt_names: &["naive realism"],
            category: BiasCategory::SelfPerception,
            description: "The belief that we see reality as it really is — objectively and without bias.",
            example: "Insisting 'I just see things as they are, unlike others who are biased.'",
            severity: Severity::High,
        },
        Bias {
            name: "False Consensus Effect",
            alt_names: &["false consensus bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency for people to overestimate the degree to which others agree with them.",
            example: "Assuming most people share your political views because your social circle does.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Spotlight Effect",
            alt_names: &["spotlight bias"],
            category: BiasCategory::SelfPerception,
            description: "The tendency to overestimate the amount that other people notice one's appearance or behaviour.",
            example: "Being overly embarrassed about a small stain on your shirt, convinced everyone has noticed.",
            severity: Severity::Low,
        },
        // ─── DECISION MAKING ──────────────────────────────────────────────────
        Bias {
            name: "Anchoring Bias",
            alt_names: &["anchoring effect", "focalism", "anchoring heuristic"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency to rely too heavily on one trait or piece of information — usually the first piece acquired — when making decisions.",
            example: "A seller listing a product at £1,000 makes £700 feel like a bargain, even if the item is worth £300.",
            severity: Severity::High,
        },
        Bias {
            name: "Sunk Cost Fallacy",
            alt_names: &["sunk cost bias", "escalation of commitment", "irrational escalation", "concorde fallacy"],
            category: BiasCategory::DecisionMaking,
            description: "Justifying increased investment in a decision based on cumulative prior investment, despite new evidence suggesting the decision was wrong.",
            example: "Continuing to watch a bad film because you already paid for the ticket.",
            severity: Severity::High,
        },
        Bias {
            name: "Loss Aversion",
            alt_names: &["loss aversion bias"],
            category: BiasCategory::DecisionMaking,
            description: "Where the perceived disutility of giving up an object is greater than the utility associated with acquiring it.",
            example: "Refusing to sell a losing stock because 'selling means accepting the loss.'",
            severity: Severity::High,
        },
        Bias {
            name: "Status Quo Bias",
            alt_names: &["status quo preference"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency to prefer things to stay relatively the same.",
            example: "Sticking with the same insurance company for years without shopping around.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Framing Effect",
            alt_names: &["framing bias"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency to draw different conclusions from the same information, depending on how that information is presented.",
            example: "Preferring '90% fat-free' yoghurt over '10% fat' yoghurt even though they are identical.",
            severity: Severity::High,
        },
        Bias {
            name: "Hyperbolic Discounting",
            alt_names: &["present bias", "current moment bias", "delay discounting"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency for people to have a stronger preference for more immediate payoffs relative to later payoffs.",
            example: "Choosing £50 today over £100 in a month.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Endowment Effect",
            alt_names: &["endowment bias", "divestiture aversion"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency for people to demand much more to give up an object than they would be willing to pay to acquire it.",
            example: "Refusing to sell a mug for £5 that you would never have paid more than £2 for.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Zero-Risk Bias",
            alt_names: &["zero risk preference"],
            category: BiasCategory::DecisionMaking,
            description: "The preference for reducing a small risk to zero over a greater reduction in a larger risk.",
            example: "Spending huge resources to eliminate a tiny risk instead of substantially reducing a large one.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Planning Fallacy",
            alt_names: &["planning bias", "optimistic planning"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency for people to underestimate the time it will take them to complete a given task.",
            example: "Expecting a software project to ship in 3 months when similar projects took 12.",
            severity: Severity::High,
        },
        Bias {
            name: "Default Effect",
            alt_names: &["default bias", "status quo default"],
            category: BiasCategory::DecisionMaking,
            description: "The tendency to favour the default option when given a choice between several options.",
            example: "Most people keeping opt-in defaults on newsletter subscriptions.",
            severity: Severity::Medium,
        },
        // ─── PROBABILITY & STATISTICS ─────────────────────────────────────────
        Bias {
            name: "Availability Heuristic",
            alt_names: &["availability bias", "availability heuristic"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to overestimate the likelihood of events with greater availability in memory.",
            example: "Overestimating the risk of plane crashes after seeing news coverage of one.",
            severity: Severity::High,
        },
        Bias {
            name: "Gambler's Fallacy",
            alt_names: &["gambler's fallacy", "monte carlo fallacy", "hot hand fallacy"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to think that future probabilities are altered by past events, when in reality they are unchanged.",
            example: "Believing a coin is 'due' to land heads after ten tails in a row.",
            severity: Severity::High,
        },
        Bias {
            name: "Clustering Illusion",
            alt_names: &["clustering bias", "hot hand phenomenon"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to overestimate the importance of small runs, streaks, or clusters in large samples of random data.",
            example: "Seeing a 'winning streak' in random sports performance data.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Base Rate Fallacy",
            alt_names: &["base rate neglect", "base rate bias"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to ignore general information and focus on information only pertaining to the specific case.",
            example: "Panicking about a 99%-accurate positive test result without considering the disease's 0.1% prevalence.",
            severity: Severity::High,
        },
        Bias {
            name: "Conjunction Fallacy",
            alt_names: &["conjunction bias", "linda problem"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to assume that specific conditions are more probable than a more general version of those same conditions.",
            example: "Believing 'Linda is a bank teller and feminist activist' is more likely than 'Linda is a bank teller.'",
            severity: Severity::Medium,
        },
        Bias {
            name: "Neglect of Probability",
            alt_names: &["probability neglect"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to completely disregard probability when making a decision under uncertainty.",
            example: "Refusing to fly due to fear but not considering it is statistically safer than driving.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Survivorship Bias",
            alt_names: &["survivorship fallacy", "survival bias"],
            category: BiasCategory::ProbabilityAndStats,
            description: "Concentrating on the people or things that 'survived' some process and inadvertently overlooking those that did not.",
            example: "Concluding startups always succeed by only reading about successful ones.",
            severity: Severity::High,
        },
        Bias {
            name: "Insensitivity to Sample Size",
            alt_names: &["sample size bias", "law of small numbers"],
            category: BiasCategory::ProbabilityAndStats,
            description: "The tendency to under-expect variation in small samples.",
            example: "Concluding a treatment works after only 3 trial participants improved.",
            severity: Severity::Medium,
        },
        // ─── SOCIAL & GROUP DYNAMICS ──────────────────────────────────────────
        Bias {
            name: "Bandwagon Effect",
            alt_names: &["bandwagon fallacy", "groupthink", "herd mentality", "herd behavior"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency to do or believe things because many other people do or believe the same.",
            example: "Buying a stock simply because 'everyone is buying it.'",
            severity: Severity::High,
        },
        Bias {
            name: "Groupthink",
            alt_names: &["group think"],
            category: BiasCategory::SocialAndGroup,
            description: "The psychological phenomenon where the desire for harmony or conformity in a group results in an irrational or dysfunctional decision-making outcome.",
            example: "A board unanimously approving a bad decision because no one wanted to dissent.",
            severity: Severity::High,
        },
        Bias {
            name: "Authority Bias",
            alt_names: &["appeal to authority"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency to attribute greater accuracy to the opinion of an authority figure and be more influenced by that opinion.",
            example: "Accepting a medical claim as true purely because a doctor said it.",
            severity: Severity::High,
        },
        Bias {
            name: "Halo Effect",
            alt_names: &["halo bias"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency for a person's good or bad traits to 'spill over' from one personality area to another in others' perceptions of them.",
            example: "Assuming an attractive person is also intelligent and kind.",
            severity: Severity::High,
        },
        Bias {
            name: "Ingroup Bias",
            alt_names: &["in-group bias", "in-group favoritism", "ingroup favoritism"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency for people to give preferential treatment to others they perceive to be members of their own groups.",
            example: "Hiring someone less qualified but from your university over a more qualified outsider.",
            severity: Severity::High,
        },
        Bias {
            name: "Outgroup Homogeneity Bias",
            alt_names: &["out-group homogeneity", "they're all the same"],
            category: BiasCategory::SocialAndGroup,
            description: "Where individuals see members of other groups as being relatively less varied than members of their own group.",
            example: "'All politicians are the same' said by someone who sees nuance within their own political party.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Fundamental Attribution Error",
            alt_names: &["correspondence bias", "attribution error"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency to overemphasise personality-based explanations for behaviours observed in others while under-emphasising situational influences.",
            example: "Assuming a slow driver is stupid rather than considering they might be lost.",
            severity: Severity::High,
        },
        Bias {
            name: "Actor-Observer Bias",
            alt_names: &["actor observer asymmetry"],
            category: BiasCategory::SocialAndGroup,
            description: "The tendency to attribute others' behaviours to their personality while attributing one's own behaviours to the situation.",
            example: "Blaming traffic for your own lateness but assuming a colleague who was late is disorganised.",
            severity: Severity::Medium,
        },
        // ─── MEMORY & RECALL ──────────────────────────────────────────────────
        Bias {
            name: "Hindsight Bias",
            alt_names: &["knew-it-all-along", "creeping determinism", "hindsight is 20/20"],
            category: BiasCategory::Memory,
            description: "The tendency to see past events as having been predictable before they happened.",
            example: "Saying 'I knew that team would win' after seeing the result.",
            severity: Severity::High,
        },
        Bias {
            name: "Rosy Retrospection",
            alt_names: &["rosy retrospection bias", "nostalgic bias"],
            category: BiasCategory::Memory,
            description: "The remembering of the past as having been better than it really was.",
            example: "Believing childhood summers were always sunny and carefree.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Misinformation Effect",
            alt_names: &["post-event information bias"],
            category: BiasCategory::Memory,
            description: "Memory becoming less accurate because of interference from post-event information.",
            example: "Eyewitnesses changing their account after being told misleading details.",
            severity: Severity::High,
        },
        Bias {
            name: "Consistency Bias",
            alt_names: &["consistency effect"],
            category: BiasCategory::Memory,
            description: "Incorrectly remembering one's past attitudes and behaviour as resembling present attitudes and behaviour.",
            example: "Believing you always supported a policy, when in fact you opposed it years ago.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Peak-End Rule",
            alt_names: &["peak end effect", "peak-end heuristic"],
            category: BiasCategory::Memory,
            description: "People seem to perceive not the sum of an experience but the average of how it was at its peak and how it ended.",
            example: "Rating a painful procedure as less bad because the final moments were mild.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Negativity Bias",
            alt_names: &["negativity effect", "negative bias"],
            category: BiasCategory::Memory,
            description: "The phenomenon of having better recall of unpleasant memories than of pleasant ones and giving negative events more weight.",
            example: "Remembering one critical piece of feedback from a performance review over ten positive ones.",
            severity: Severity::High,
        },
        Bias {
            name: "Cryptomnesia",
            alt_names: &["cryptamnesia"],
            category: BiasCategory::Memory,
            description: "Where a memory is mistaken for novel thought or imagination.",
            example: "Believing you invented an idea that you actually read somewhere years ago.",
            severity: Severity::Low,
        },
        Bias {
            name: "False Memory",
            alt_names: &["false memories", "fabricated memory"],
            category: BiasCategory::Memory,
            description: "Where imagination is mistaken for a memory.",
            example: "Vividly 'remembering' an event that never happened because you were told about it many times.",
            severity: Severity::High,
        },
        Bias {
            name: "Choice-Supportive Bias",
            alt_names: &["choice supportive memory"],
            category: BiasCategory::Memory,
            description: "The tendency to remember one's choices as better than they actually were.",
            example: "Remembering a car you bought as having fewer problems than it really did.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Fading Affect Bias",
            alt_names: &["fading affect"],
            category: BiasCategory::Memory,
            description: "A bias in which the emotion associated with unpleasant memories fades more quickly than the emotion associated with pleasant ones.",
            example: "Forgetting how upset a holiday argument made you, while fondly recalling the sightseeing.",
            severity: Severity::Low,
        },
        // ─── MEANING-MAKING ───────────────────────────────────────────────────
        Bias {
            name: "Apophenia",
            alt_names: &["apophany", "pattern recognition bias"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency to perceive meaningful connections between unrelated things.",
            example: "Seeing faces in clouds or finding hidden messages in random text.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Pareidolia",
            alt_names: &["pareidollia"],
            category: BiasCategory::MeaningMaking,
            description: "A tendency to perceive a vague and random stimulus as significant.",
            example: "Seeing the face of Jesus in a piece of toast.",
            severity: Severity::Low,
        },
        Bias {
            name: "Illusion of Control",
            alt_names: &["control illusion", "perceived control"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency to overestimate one's degree of influence over other external events.",
            example: "Blowing on dice before rolling, believing it affects the outcome.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Teleological Bias",
            alt_names: &["teleological thinking", "intentionality bias"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency to engage in overgeneralised ascriptions of purpose to entities and events.",
            example: "Assuming 'trees grow leaves to provide shade for animals.'",
            severity: Severity::Low,
        },
        Bias {
            name: "Curse of Knowledge",
            alt_names: &["curse of expertise", "knowledge curse"],
            category: BiasCategory::MeaningMaking,
            description: "When better-informed people find it extremely difficult to think about problems from the perspective of lesser-informed people.",
            example: "An expert writing documentation that only other experts can understand.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Barnum Effect",
            alt_names: &["forer effect", "barnum-forer effect", "personal validation fallacy"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency for individuals to give high accuracy ratings to descriptions of their personality that are vague and general enough to apply to a wide range of people.",
            example: "Thinking a horoscope is surprisingly accurate when it applies to almost anyone.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Just-World Fallacy",
            alt_names: &["just world hypothesis", "just world bias"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency to want to believe that the world is fundamentally just, causing people to rationalise an injustice as deserved by the victim.",
            example: "Assuming a crime victim must have done something to deserve it.",
            severity: Severity::High,
        },
        Bias {
            name: "Proportionality Bias",
            alt_names: &["proportionality fallacy"],
            category: BiasCategory::MeaningMaking,
            description: "Our innate tendency to assume that big events have big causes.",
            example: "Believing a major historical event must have been orchestrated by a powerful conspiracy.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Pro-Innovation Bias",
            alt_names: &["technology bias", "novelty bias", "shiny object syndrome"],
            category: BiasCategory::MeaningMaking,
            description: "The tendency to have excessive optimism towards an invention or innovation's usefulness throughout society.",
            example: "Assuming a new technology will solve a social problem without examining its limitations.",
            severity: Severity::Medium,
        },
        // ─── RECENCY & SALIENCE ───────────────────────────────────────────────
        Bias {
            name: "Recency Bias",
            alt_names: &["recency effect", "recency illusion"],
            category: BiasCategory::RecencyAndSaliency,
            description: "The tendency to weigh recent events more heavily than historical ones.",
            example: "Selling investments after a market drop, ignoring long-term performance history.",
            severity: Severity::High,
        },
        Bias {
            name: "Salience Bias",
            alt_names: &["salience effect", "vividness bias"],
            category: BiasCategory::RecencyAndSaliency,
            description: "The tendency to focus on items that are more prominent or emotionally striking.",
            example: "Prioritising a loudly-voiced complaint over quieter but more prevalent feedback.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Frequency Illusion",
            alt_names: &["baader-meinhof phenomenon", "baader meinhof effect", "frequency bias"],
            category: BiasCategory::RecencyAndSaliency,
            description: "Once something has been noticed, every instance of that thing is noticed, leading to the belief it has a high frequency of occurrence.",
            example: "After buying a red car, seeing red cars everywhere.",
            severity: Severity::Low,
        },
        Bias {
            name: "Primacy Effect",
            alt_names: &["primacy bias", "first impression effect"],
            category: BiasCategory::RecencyAndSaliency,
            description: "Where an item at the beginning of a list is more easily recalled.",
            example: "Remembering the first speaker at a conference most vividly.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Serial Position Effect",
            alt_names: &["serial position bias"],
            category: BiasCategory::RecencyAndSaliency,
            description: "Items near the end of a sequence are easiest to recall, followed by items at the beginning; items in the middle are least likely to be remembered.",
            example: "Remembering the first and last items on a to-do list but forgetting the middle ones.",
            severity: Severity::Low,
        },
        Bias {
            name: "Telescoping Effect",
            alt_names: &["telescoping bias", "forward telescoping", "backward telescoping"],
            category: BiasCategory::RecencyAndSaliency,
            description: "The tendency to displace recent events backwards in time and remote events forward in time.",
            example: "Feeling like a major event from 5 years ago happened just recently.",
            severity: Severity::Low,
        },
        // ─── ACTION & INERTIA ─────────────────────────────────────────────────
        Bias {
            name: "Action Bias",
            alt_names: &["doing bias", "intervention bias"],
            category: BiasCategory::ActionBias,
            description: "The tendency for someone to act when faced with a problem even when inaction would be more effective.",
            example: "A goalkeeper diving to one side during a penalty, even though staying central is statistically better.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Omission Bias",
            alt_names: &["omission effect", "act-omission distinction"],
            category: BiasCategory::ActionBias,
            description: "The tendency to judge harmful actions as worse, or less moral, than equally harmful inactions.",
            example: "Viewing someone who pushed a trolley to save five lives as worse than someone who did nothing.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Restraint Bias",
            alt_names: &["restraint overestimation"],
            category: BiasCategory::ActionBias,
            description: "The tendency to overestimate one's ability to show restraint in the face of temptation.",
            example: "Buying junk food believing you will 'only eat a little', then finishing the whole packet.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Normalcy Bias",
            alt_names: &["normality bias", "analysis paralysis", "ostrich effect"],
            category: BiasCategory::ActionBias,
            description: "The refusal to plan for, or react to, a disaster which has never happened before.",
            example: "Failing to evacuate during an early warning because 'it has never been that bad before.'",
            severity: Severity::High,
        },
        Bias {
            name: "Plan Continuation Bias",
            alt_names: &["plan continuation", "press-on-regardless"],
            category: BiasCategory::ActionBias,
            description: "Failure to recognise that the original plan of action is no longer appropriate for a changing situation.",
            example: "A pilot continuing to fly into deteriorating weather because 'the plan was to land at this airport.'",
            severity: Severity::High,
        },
        Bias {
            name: "Functional Fixedness",
            alt_names: &["design fixation", "functional fixity"],
            category: BiasCategory::ActionBias,
            description: "A tendency limiting a person to using an object only in the way it is traditionally used.",
            example: "Using only a hammer when a heavy book would work just as well.",
            severity: Severity::Low,
        },
        Bias {
            name: "Not Invented Here",
            alt_names: &["NIH syndrome", "not invented here bias"],
            category: BiasCategory::ActionBias,
            description: "An aversion to contact with or use of products, research, standards, or knowledge developed outside a group.",
            example: "A company rewriting libraries from scratch rather than using proven open-source solutions.",
            severity: Severity::Medium,
        },
        // ─── CAUSAL ATTRIBUTION ───────────────────────────────────────────────
        Bias {
            name: "Hostile Attribution Bias",
            alt_names: &["hostile attribution", "hostile intent attribution"],
            category: BiasCategory::CausalAttribution,
            description: "The tendency to interpret others' behaviours as having hostile intent, even when the behaviour is ambiguous or benign.",
            example: "Assuming a colleague's terse email was an attack, when they were simply busy.",
            severity: Severity::High,
        },
        Bias {
            name: "System Justification",
            alt_names: &["system justification bias"],
            category: BiasCategory::CausalAttribution,
            description: "The tendency to defend and bolster the status quo.",
            example: "Defending unfair institutional policies simply because 'that's how it's always been done.'",
            severity: Severity::Medium,
        },
        Bias {
            name: "Egocentric Bias",
            alt_names: &["egocentric attribution"],
            category: BiasCategory::CausalAttribution,
            description: "Recalling the past in a self-serving manner, e.g., remembering one's exam grades as being better than they were.",
            example: "Remembering you contributed more to a group project than your teammates recall.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Group Attribution Error",
            alt_names: &["group attribution bias"],
            category: BiasCategory::CausalAttribution,
            description: "The biased belief that the characteristics of an individual group member are reflective of the group as a whole.",
            example: "Concluding all members of a nationality are rude after meeting one rude person from there.",
            severity: Severity::High,
        },
        Bias {
            name: "Defensive Attribution Hypothesis",
            alt_names: &["defensive attribution"],
            category: BiasCategory::CausalAttribution,
            description: "A tendency to attribute more blame for a mishap to the person involved if they are perceived as dissimilar to the person making the judgment.",
            example: "Judging a distant stranger's accident more harshly than a similar accident by someone like you.",
            severity: Severity::Medium,
        },
        Bias {
            name: "Illusion of Explanatory Depth",
            alt_names: &["illusion of understanding", "explanatory depth illusion"],
            category: BiasCategory::CausalAttribution,
            description: "The tendency to believe that one understands a topic much better than one actually does.",
            example: "Believing you could explain how a zipper works, but struggling to actually do so.",
            severity: Severity::Medium,
        },
        Bias {
            name: "G.I. Joe Fallacy",
            alt_names: &["knowing is half the battle", "gi joe fallacy"],
            category: BiasCategory::CausalAttribution,
            description: "The tendency to think that knowing about cognitive bias is enough to overcome it.",
            example: "Saying 'I know about confirmation bias, so I'm immune to it.'",
            severity: Severity::Medium,
        },
    ]
});
