/// Keyword patterns used for rule-based bias detection.
/// Each entry maps a bias name to a list of trigger phrase patterns.
/// These are matched using word-boundary aware substring matching (case-insensitive).

pub struct Pattern {
    pub bias_name: &'static str,
    pub keywords: &'static [&'static str],
    pub phrases: &'static [&'static str],
    /// Weight multiplier 1–5 (phrases score higher than keywords)
    pub phrase_weight: u8,
}

pub static PATTERNS: &[Pattern] = &[
    Pattern {
        bias_name: "Confirmation Bias",
        keywords: &["everyone knows", "obviously", "clearly proves", "as expected", "proves my point",
                    "always knew", "told you so", "i was right"],
        phrases: &["confirms what i", "supports my view", "just as i thought", "this proves that",
                   "only shows that", "i already knew", "proves i was right"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Anchoring Bias",
        keywords: &["starting from", "originally priced", "first offer", "baseline of",
                    "benchmark of", "reference point"],
        phrases: &["compared to the original", "relative to the asking price",
                   "the initial number was", "starting price was", "the anchor is"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Availability Heuristic",
        keywords: &["i've seen so many", "it's everywhere", "i keep hearing about",
                    "seems very common", "seems to happen all the time"],
        phrases: &["because i just saw", "since i read about it recently",
                   "i remember when", "it's all over the news", "i keep seeing"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Sunk Cost Fallacy",
        keywords: &["wasted", "already spent", "can't give up now", "come too far",
                    "invested too much", "too much to lose", "after all this work"],
        phrases: &["i've already put in", "can't quit now", "we've come so far",
                   "too much invested", "after all we've spent", "sunk too much into",
                   "after everything i've", "waste all that effort"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Dunning-Kruger Effect",
        keywords: &["easy", "simple", "anyone could", "not that hard", "don't need experts",
                    "how hard can it be", "straightforward"],
        phrases: &["how hard can it", "i could do that easily", "don't need a professional",
                   "experts are overthinking", "it's really not that complicated",
                   "just use common sense"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Bandwagon Effect",
        keywords: &["everyone is doing", "everyone says", "everyone thinks", "most people agree",
                    "popular opinion", "everybody knows", "mainstream"],
        phrases: &["all my friends think", "everyone i know", "people are all saying",
                   "the majority believe", "if everyone else is doing it",
                   "so many people can't be wrong"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Survivorship Bias",
        keywords: &["success story", "all successful", "winners always", "proof it works"],
        phrases: &["look at all the successful", "all the great companies started",
                   "if they succeeded anyone can", "you only hear about the wins",
                   "no one talks about the failures"],
        phrase_weight: 5,
    },
    Pattern {
        bias_name: "Hindsight Bias",
        keywords: &["obviously", "saw it coming", "could have predicted", "knew it",
                    "should have known", "anyone could see"],
        phrases: &["i knew that would happen", "it was obvious all along",
                   "we should have seen this coming", "in retrospect it was clear",
                   "looking back it was inevitable", "saw it coming from a mile"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Overconfidence Effect",
        keywords: &["100% sure", "absolutely certain", "there is no doubt", "guaranteed",
                    "without question", "undeniably", "definitely"],
        phrases: &["i am completely certain", "there is no way i'm wrong",
                   "i know for a fact", "there's absolutely no doubt",
                   "i'm 100% confident", "impossible that i'm wrong"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Authority Bias",
        keywords: &["expert says", "scientist says", "doctor says", "study shows",
                    "research shows", "the government says", "official"],
        phrases: &["because the expert said", "the authority on this says",
                   "they have a phd", "the ceo said so", "it must be true because",
                   "the study found that so it must"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "False Consensus Effect",
        keywords: &["most people", "everyone agrees", "nobody disagrees", "common sense"],
        phrases: &["most people would agree", "anyone reasonable would",
                   "it's just common sense that", "i don't know anyone who disagrees",
                   "who would disagree with"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Framing Effect",
        keywords: &["90% fat free", "nearly all", "only 10%", "just", "merely",
                    "as many as", "up to"],
        phrases: &["when you think of it as", "if you look at it from",
                   "framed as a loss", "framed as a gain", "described as"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Planning Fallacy",
        keywords: &["should only take", "won't take long", "quick task", "just a few hours",
                    "be done by", "easily finish"],
        phrases: &["we'll be done in no time", "it's a quick job",
                   "won't take more than", "should be finished well before",
                   "easy to complete in", "simple two-week task"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Gambler's Fallacy",
        keywords: &["due for", "overdue", "can't keep losing", "bound to win",
                    "streak must end", "long overdue"],
        phrases: &["it's due to come up", "can't lose forever",
                   "after this many losses it must", "the streak has to end",
                   "we're bound to win next time", "due a win"],
        phrase_weight: 5,
    },
    Pattern {
        bias_name: "Loss Aversion",
        keywords: &["can't afford to lose", "too much to lose", "terrified of losing",
                    "hate to lose", "avoid losing"],
        phrases: &["the risk of losing is too", "i'd rather not lose",
                   "can't risk losing that", "nothing is worse than losing",
                   "i won't risk losing", "fear of loss"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Halo Effect",
        keywords: &["great person", "amazing leader", "wonderful human being",
                    "brilliant at everything", "perfect"],
        phrases: &["because they're so good at one thing they must",
                   "such a great person that", "talented person so they must also",
                   "wonderful in every way", "brilliant at everything"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Fundamental Attribution Error",
        keywords: &["that kind of person", "that's just who they are", "lazy", "careless",
                    "reckless person", "incompetent"],
        phrases: &["they're just lazy", "that's just how they are",
                   "it's because of the type of person", "he's just that kind of",
                   "she's always been that way", "typical of them"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Recency Bias",
        keywords: &["lately", "recently", "just happened", "right now", "these days",
                    "nowadays", "in recent times"],
        phrases: &["because it just happened", "things are always like this lately",
                   "the recent trend shows", "based on what happened last week",
                   "everything has been terrible recently"],
        phrase_weight: 2,
    },
    Pattern {
        bias_name: "Negativity Bias",
        keywords: &["worst ever", "terrible", "nothing works", "always goes wrong",
                    "never get anything right", "complete disaster"],
        phrases: &["nothing ever goes right", "it's always something bad",
                   "why does everything go wrong", "can't catch a break",
                   "always the worst outcome", "everything is falling apart"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Normalcy Bias",
        keywords: &["never happened before", "won't be that bad", "no need to panic",
                    "it'll be fine", "we've always been okay"],
        phrases: &["it can't happen here", "things will go back to normal",
                   "no need to prepare", "it's never been that serious before",
                   "we'll be fine like always"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Ingroup Bias",
        keywords: &["one of us", "our team", "my people", "we stick together",
                    "my group", "our kind"],
        phrases: &["people from our group", "we take care of our own",
                   "because they're on our side", "one of our own people",
                   "we look after our own"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Just-World Fallacy",
        keywords: &["deserved it", "karma", "asked for it", "their fault",
                    "reap what you sow", "got what was coming"],
        phrases: &["they brought it on themselves", "must have done something to deserve",
                   "the universe has a way of", "what goes around comes around",
                   "people get what they deserve", "had it coming"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Illusory Superiority",
        keywords: &["above average", "better than most", "smarter than average",
                    "not like most people", "most people can't", "unlike the others"],
        phrases: &["i'm better than the average person", "most people can't do what i do",
                   "unlike most people i", "i'm not like the majority",
                   "above the average level"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Pro-Innovation Bias",
        keywords: &["game changer", "revolutionary", "will solve everything",
                    "change the world", "disrupts everything", "AI will fix"],
        phrases: &["this technology will change everything", "this innovation solves all",
                   "the future is here and it will", "this will revolutionize"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Proportionality Bias",
        keywords: &["can't be a coincidence", "too big to be random",
                    "something bigger at play", "obviously planned", "orchestrated"],
        phrases: &["something this big must have been", "can't be an accident",
                   "someone planned this", "too many coincidences"],
        phrase_weight: 5,
    },
    Pattern {
        bias_name: "Status Quo Bias",
        keywords: &["always done it this way", "don't fix what isn't broken",
                    "tradition", "change is bad", "stick with what works",
                    "if it ain't broke"],
        phrases: &["we've always done it this way", "there's no need to change",
                   "worked before so let's keep", "no reason to fix it"],
        phrase_weight: 3,
    },
    Pattern {
        bias_name: "Hostile Attribution Bias",
        keywords: &["did that on purpose", "deliberately", "intentionally ignored",
                    "meant to hurt", "passive aggressive"],
        phrases: &["they did that on purpose", "clearly meant to offend",
                   "deliberately trying to", "they knew what they were doing",
                   "it was a deliberate slight"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Base Rate Fallacy",
        keywords: &["must mean", "proves that all", "one case shows",
                    "therefore all", "that single example"],
        phrases: &["just because one person did", "this one case proves",
                   "based on this single example", "if it happened once it must"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Illusion of Control",
        keywords: &["lucky charm", "ritual", "makes a difference", "if i do this",
                    "controls the outcome"],
        phrases: &["if i always do this i win", "my ritual ensures",
                   "this lucky object helps me", "as long as i do this"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "Not Invented Here",
        keywords: &["build it ourselves", "can't trust external", "in-house only",
                    "don't need their solution", "write our own"],
        phrases: &["we should build our own", "can't use external libraries",
                   "better to reinvent the wheel", "don't trust solutions made elsewhere"],
        phrase_weight: 4,
    },
    Pattern {
        bias_name: "G.I. Joe Fallacy",
        keywords: &["knowing about bias", "aware of the bias", "i know this bias",
                    "immune to bias", "can't affect me"],
        phrases: &["since i know about this bias", "knowing the bias means i won't",
                   "i've studied biases so", "awareness means i'm not affected"],
        phrase_weight: 5,
    },
];
